//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogPermission()
        {
            this.CapPheps = new HashSet<CapPhep>();
        }
    
        public int PermissionId { get; set; }
        public string PermisstionName { get; set; }
        public string Description { get; set; }
        public string MaNghiepVu { get; set; }
    
        public virtual NghiepVu NghiepVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapPhep> CapPheps { get; set; }
    }
}
