//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietSanPhams = new HashSet<ChiTietSanPham>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public Double GiaBan { get; set; }
        public int SoLuongTon { get; set; }
        public Nullable<int> SanPhamMoi { get; set; }
        public string MaLoai { get; set; }
        public string MaNCC { get; set; }
        public string ThanhToanTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSanPham> ChiTietSanPhams { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
